name: PR Security

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  semgrep:
    name: Semgrep (SAST)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Semgrep
        run: pipx install semgrep || pip install --user semgrep

      - name: Run Semgrep (auto rules)
        env:
          # Optional: if set, results also appear in semgrep.dev dashboard
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        run: semgrep ci --config auto

  checkov:
    name: Checkov (IaC)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Detect Terraform folder
        id: detect_tf
        run: |
          if [ -d infra/terraform ]; then
            echo "has_tf=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_tf=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Install Checkov
        if: steps.detect_tf.outputs.has_tf == 'true'
        run: pipx install checkov || pip install --user checkov

      - name: Scan Terraform with Checkov
        if: steps.detect_tf.outputs.has_tf == 'true'
        run: checkov -d infra/terraform --quiet

      - name: Skip (no infra/terraform found)
        if: steps.detect_tf.outputs.has_tf != 'true'
        run: echo "Skipping Checkov: no infra/terraform directory."
