name: PR Security & Cost
on:
  pull_request: { branches: [main] }
  push:
    branches: ["feature/**", "bugfix/**", "chore/**"] # optional

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# These permissions let Infracost post a PR comment.
permissions:
  contents: read
  pull-requests: write

jobs:
  semgrep:
    name: Semgrep (SAST)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Semgrep
        run: pipx install semgrep || pip install --user semgrep
      - name: Run Semgrep
        # If you added SEMGREP_APP_TOKEN, Semgrep will upload to semgrep.dev
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }} # optional
        run: semgrep ci --config auto

  checkov:
    name: Checkov (IaC)
    if: ${{ hashFiles('infra/terraform/**') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Checkov
        run: pipx install checkov || pip install --user checkov
      - name: Scan Terraform
        run: checkov -d infra/terraform --quiet

  infracost:
    name: Infracost (Cost)
    if: ${{ hashFiles('infra/terraform/**') != '' && secrets.INFRACOST_API_KEY != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Infracost
        run: curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
      - name: Infracost breakdown
        env:
          INFRACOST_API_KEY: ico-L77peDwqm1ChsL1MazL719JaPlGXC34G
        run: infracost breakdown --path infra/terraform --format json --out-file infracost.json
      - name: Comment PR with cost diff
        env:
          INFRACOST_API_KEY: ico-L77peDwqm1ChsL1MazL719JaPlGXC34G
        run: |
          infracost comment github --path infracost.json \
            --repo ${{ github.repository }} \
            --pull-request ${{ github.event.pull_request.number }} \
            --behavior update
      - name: Upload Infracost artifact
        uses: actions/upload-artifact@v4
        with:
          name: infracost
          path: infracost.json
